name: Build Java Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Usar el runner autohospedado
    labels: [self-hosted, Linux, X64]  # Etiquetas del runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check and Install specific Maven version
      run: |
        MAVEN_VERSION=3.8.6
        MAVEN_DIR=/opt/apache-maven-${MAVEN_VERSION}
        
        # Validar si Maven ya está instalado
        if [ -d "$MAVEN_DIR" ]; then
          echo "Maven ${MAVEN_VERSION} ya está instalado."
        else
          echo "Instalando Maven ${MAVEN_VERSION}..."
          curl -sL https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -o maven.tar.gz
          tar xzvf maven.tar.gz -C /opt/
          sudo ln -sf /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/bin/mvn
        fi
        
        # Verificar la instalación de Maven
        mvn -v

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install
